version: '3.8'

networks:
  microservice-network:
    driver: bridge
  frontend-network:
    driver: bridge

services:

  cv-builder-client:
    build:
      context: ./services/cv-builder/client
      dockerfile: ${DOCKERFILE}
    container_name: cv-builder-client
    volumes:
      - ./services/cv-builder/client/src:/opt/app/client/src
      - /opt/app/client/node_modules
    tty: true
    stdin_open: true
    environment:
      CLIENT_PORT: ${INTERNAL_APP_PORT}
      CHOKIDAR_USEPOLLING: true
      LOCAL_HOST: '0.0.0.0' # Docker local host
    ports:
      - ${CV_BUILDER_EXTERNAL_PORT}:${INTERNAL_APP_PORT}
    networks:
      - microservice-network
      - frontend-network